api_version = 1
version = "1.2.0"
fut = ">=0.14.0, <1.0.0"
capabilities = ["commands", "hooks", "presentation_tokens"]
id = "run"

[commands.restart]
title = "Restart run command"
argv = ["./bin/runctl", "restart"]
mode = "background"

[commands.stop]
title = "Stop run command"
argv = ["./bin/runctl", "stop"]
mode = "background"

[commands.logs]
title = "Run logs"
argv = ["./bin/runctl", "logs"]

[commands.edit-logs]
title = "Edit run logs"
argv = ["./bin/runctl", "edit-logs"]

[hooks]
"session.created" = ["./bin/runctl", "hook"]
"workspace.created" = ["./bin/runctl", "hook"]
"workspace.closed" = ["./bin/runctl", "hook"]

[[presentation_tokens]]
name = "status"
scope = "workspace"

[presentation_tokens.variants.pause]
text = "⚬"
nerd_font_text = "󰒓"
style = "muted"

[presentation_tokens.variants.launching]
text = "⁕"
nerd_font_text = "󱑠"
style = "attention"
presentation = "pulse"

[presentation_tokens.variants.play]
text = "‣"
nerd_font_text = "󱤵"
style = "added"

[presentation_tokens.variants.stop]
text = "☒"
nerd_font_text = "󱤷"
style = "divider"

[presentation_tokens.variants.cross]
text = "✗"
style = "error"
