api_version = 1
version = "1.0.0"
fut = ">=0.7.0, <1.0.0"
capabilities = ["commands", "hooks", "presentation_tokens"]
id = "run"

[commands.restart]
title = "Restart run command"
argv = ["./bin/runctl", "restart"]
mode = "background"

[commands.stop]
title = "Stop run command"
argv = ["./bin/runctl", "stop"]
mode = "background"

[commands.logs]
title = "Run logs"
argv = ["./bin/runctl", "logs"]

[commands.edit-logs]
title = "Edit run logs"
argv = ["./bin/runctl", "edit-logs"]

[hooks]
"workspace.created" = ["./bin/runctl", "hook"]
"workspace.closed" = ["./bin/runctl", "hook"]

[[presentation_tokens]]
name = "pause"
scope = "workspace"

[[presentation_tokens]]
name = "launching"
scope = "workspace"
presentation = "spinner"

[[presentation_tokens]]
name = "play"
scope = "workspace"

[[presentation_tokens]]
name = "stop"
scope = "workspace"

[[presentation_tokens]]
name = "cross"
scope = "workspace"

[[presentation_tokens]]
name = "status"
scope = "workspace"
