api_version = 1
version = "1.0.0"
fut = ">=0.7.0, <1.0.0"
capabilities = ["hooks", "presentation_tokens"]
id = "example-workspace-status"

[hooks]
"workspace.created" = ["./bin/workspace-event"]
"workspace.renamed" = ["./bin/workspace-event"]

[[presentation_tokens]]
name = "last_event"
scope = "workspace"
