title: Fut
description: Agent-aware terminal multiplexing
url: https://fut.sh
baseurl: ""
repository: mikker/fut
version: "0.11"
markdown: kramdown
permalink: pretty
relative_links:
  enabled: true
  collections: true
plugins:
  - jekyll-relative-links
exclude:
  - README.md
